---
- name: Install apt deps
  become: yes
  apt:
    name: [ca-certificates, curl, gnupg]
    state: present
    update_cache: yes

- name: Install Docker using convenience script
  become: yes
  shell: curl -fsSL https://get.docker.com | sh

- name: Install docker-compose plugin
  become: yes
  apt:
    name: docker-compose-plugin
    state: present

- name: Add {{ ansible_user }} to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
